// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------- //
// sbus_rx //
// ------- //

#define sbus_rx_wrap_target 0
#define sbus_rx_wrap 5
#define sbus_rx_pio_version 0

static __pio_const uint16_t sbus_rx_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0xea27, //  1: set    x, 7                   [10]
    0x4001, //  2: in     pins, 1
    0x0642, //  3: jmp    x--, 2                 [6]
    0x8720, //  4: push   block                  [7]
    0x20a0, //  5: wait   1 pin, 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program sbus_rx_program = {
    .instructions = sbus_rx_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = sbus_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config sbus_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sbus_rx_wrap_target, offset + sbus_rx_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
// pin = the SBUS RX GPIO (GP6). baud = 100000.
static inline void sbus_rx_program_init(PIO pio, uint sm, uint offset,
                                        uint pin, float baud) {
    pio_gpio_init(pio, pin);
    // ---- SOFTWARE INVERSION: invert the pad input so PIO sees normal uart ----
    gpio_set_inover(pin, GPIO_OVERRIDE_INVERT);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false);  // pin = input
    pio_sm_config c = sbus_rx_program_get_default_config(offset);
    sm_config_set_in_pins(&c, pin);              // IN + WAIT read this pin
    sm_config_set_in_shift(&c, true, false, 8);  // shift RIGHT, manual push, thresh 8
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);  // 8-deep RX FIFO
    // 8 SM cycles per bit.
    float div = (float)clock_get_hz(clk_sys) / (8.0f * baud);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

